### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by tanvirr007** [euclid-Devices/official_devices#3]
## Name and Codename of the device you want to apply for
```
Redmi Note 11 (spes/n)
```

## Device Tree sources

```
https://github.com/spes-development/device_xiaomi_spes
https://github.com/spes-development/kernel_xiaomi_sm6225
https://github.com/spes-development/vendor_xiaomi_spes
```

## What ROM's do you maintain officially/unofficially
```
The Pixel Project officially
```

## How long have you been building Custom ROMs
```
Almost 1 year
```

## Do you build locally or rely on server if server what cloud service provider do you use ?
```
Cloud server
```
## Free trial user or paid user?
```
Paid
```

### Telegram username
```
tanvirr007
```

### GitHub username
```
tanvirr007
```

### [MUST] Link to your XDA thread of unofficial build

```
N/A
```

### [MUST] Link to your unofficial EuclidOS Build Post other than XDA

```
https://t.me/RedmiNote11_Updates/549
```

**Comment by Arijit78** [comment]
Greetings from Team EuclidOS,

We are happy to inform you that your application for Official Maintainership is accepted
